[connections.supabase]
SUPABASE_URL = "https://tydajxfgpjgilduyovcz.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5ZGFqeGZncGpnaWxkdXlvdmN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTU3NDU5MTksImV4cCI6MjAxMTMyMTkxOX0.sQMhCm32u2sKLbaWs8c8Pz0zvJ3eLNQMxZJHA-FwOOw"